---
title: "Group meeting notes"
format: html
---

### Meeting 03/20/2026
#### Discussions
- 1. Use the WEIGHT column in the model to adjust data close to the population?

The weight tells you:
How many people in the U.S. population this respondent represen ts. So instead of treating every observation equally, you scale them.
Example:
Respondent A: weight = 500
Respondent B: weight = 2,000
👉 B represents 4× more people than A in the population.

```{R}
#| eval: false
lm(Y ~ X1 + X2, data = df, weights = weight)
```

**Discussion:**

- 2. There are multiple questions indicting similar metrics such as age, education, region, financial condition, income, employment status. Sync across memebers which ones to use.

**Discussion:**

- 3. Shall we add up multiple total monthly payment variables to get the total monthly payment measure? (rental + loans + other)

**Discussion:**

- 4. Which variable to use as retirement_flag? (D22_i, D1i)

**Discussion:**

- 5. Which variable to use as credit health? (A6, ppfs1482, A1_abc)

**Discussion:**

- 6. Which variable to use as financial situation (better or worse) ?

**Discussion:**

- 7. Which variable to use education level? (ED0, ppeduc5)

**Discussion:**

- 8. Which variable to use as Race?
**Discussion:**

- 9. income amt? (ppinc7, I40)
**Discussion:**

#### Method
 - 1. columns used for EDA:

| Variable   | Question | Correlation with BNPL1 | Category |
|--------|-----|-----|-----|
| B3  | financial health | Y |
| X12_abcdefg | financial concern flag | X12_e Y |
| ppgender | gender | N |
| CG2 | weekly Childcare expense | | monthly payment |
| SL4 | monthly student loan payment | | monthly payment |
| M4 | monthly mortgage payment | | monthly payment |
| I40 | 12 months personal income amt | | income amt |
| D22_i, D1i | retired flag | N |
| R1_abcdefgh | renting house flag |
| A6  | credit application confidence |
| A1_abc | credit card application issue |
| AB_abcdef | loan application failure flag |
| C3P, C4A | credit card default |
| BNPL1 | BNPL flag |
| BNPL3, BNPL3A | BNPL default |
| BNPL4_abcdefg | BNPL reason |
| ED0, ppeduc5, ED0_orig | education |
| SL3 | total student loans amt |
| SL6 | loans default flag |
| SL4A | loan flag |
| I0_abcdef | Income flag |
| ppemploy | employment flag |
| INF4 | financial health |
| I9 | income statbility |
| I21_a | income increase flag |
| I21_b | spending increase flag |
| EF1, EF2 | emergency fund flag |
| EF5C | Bill default flag |
| ppage | age |
| ppethm, ppracem, pphispan | race | ppethm Y |
| ppinc7 | household income |
| ppmarit5 | marital status | N |
| ppfs1482 | credit score |
| R3 | monthly rental expense paid by parent/spouse/partner/self |
